// Constructor quick-start presets — React-free domain module.
//
// Presets are a *UX shortcut*: they let a client start from a ready-made item
// configuration (a box with a lid, a sectioned organizer, a panel with holes, …)
// instead of an empty form. They are NOT a persisted concept — no preset id ever
// reaches the payload, the schema, or the backend. The picker keeps only local
// React state; `applyConstructorPresetValues` produces a fresh, fully-shaped
// `PrintRequestInput` that the wizard feeds straight into `react-hook-form`.
//
// Design rules (shared with design.ts / accessories.ts / lid.ts):
//   - no React, no DOM, no three.js imports here;
//   - element / accessory ids are generated by the factory helpers, which are
//     only ever invoked from `applyConstructorPresetValues` (called inside an
//     event handler — never during render / SSR), so the non-deterministic id
//     fallback stays hydration-safe;
//   - applying a preset preserves the user's contact details, comment, purpose
//     and reference text — only the *constructor* fields are replaced;
//   - the legacy `shape` / `cornerRadiusMm` fields are mirrored from the chosen
//     base shape so the existing 2D/3D previews and server validation keep
//     working unchanged.

import type { PrintRequestInput } from "@/lib/validations/print-request";
import {
  DEFAULT_DESIGN_BASE_SHAPE,
  baseKindToLegacyShape,
  createDesignElement,
  createFastenerElements,
  createHoleElement,
  createTextDecorationElement,
  type BaseShapeKind,
  type DesignElement,
  type DesignSettings,
} from "@/lib/design";
import {
  createDefaultAppearance,
  type Appearance,
  type TextPlacement,
} from "@/lib/appearance";
import { createDefaultLid, type LidSettings } from "@/lib/lid";
import { createHandleAccessory, type Accessory } from "@/lib/accessories";

// ---- Ids -------------------------------------------------------------------

export const CONSTRUCTOR_PRESET_IDS = [
  "boxWithLid",
  "sectionedOrganizer",
  "panelWithHoles",
  "textPlaque",
  "blank",
] as const;
export type ConstructorPresetId = (typeof CONSTRUCTOR_PRESET_IDS)[number];

// ---- Preset declaration ----------------------------------------------------

/**
 * Static, declarative slice of a preset. A plain `Partial<PrintRequestInput>`
 * (no `any`, no deep-partial gymnastics): a preset only ever sets a handful of
 * top-level constructor fields, and the *dynamic* bits that need generated ids
 * (design elements, accessories) are produced by `applyConstructorPresetValues`
 * from the intent already encoded here (`hasHoles`, `hasFasteners`,
 * `appearance.textDecoration.enabled`, …) plus the preset-level `frontHandles`
 * count below. Storing pre-built elements/accessories here would generate ids at
 * module-load time, which we deliberately avoid.
 */
export type ConstructorPresetValues = Partial<PrintRequestInput>;

export interface ConstructorPreset {
  id: ConstructorPresetId;
  title: string;
  description: string;
  /** Short "good for …" line shown under the description. */
  recommendedFor: string;
  /** 2–3 short tags rendered as chips on the card. */
  chips: readonly string[];
  /** Declarative static field values applied on top of the constructor defaults. */
  values: ConstructorPresetValues;
  /**
   * Number of front-mounted handles to create when this preset is applied. The
   * accessories themselves (with fresh ids) are built in
   * `applyConstructorPresetValues`, never at module load.
   */
  frontHandles?: number;
}

// ---- Fields preserved across a preset apply --------------------------------
//
// Everything the user typed that describes *who they are* / *what they want* but
// not the item geometry. A preset never silently discards these.
const PRESERVED_FIELDS = [
  "purpose",
  "usageEnvironment",
  "referenceDescription",
  "optionalReferenceLinks",
  "clientComment",
  "clientName",
  "clientEmail",
  "clientPhone",
  "preferredContactTime",
  "consentPersonalData",
  // Material catalogue choices are user context, not geometry — keep them.
  "material",
  "color",
  "strength",
] as const satisfies readonly (keyof PrintRequestInput)[];

// Normalized centres per text-face, matching the Features-step defaults. Kept
// local (a tiny domain constant) so this module stays free of any React import.
const TEXT_PLACEMENT_CENTER: Record<TextPlacement, { x: number; y: number }> = {
  front: { x: 0.5, y: 0.8 },
  back: { x: 0.5, y: 0.2 },
  left: { x: 0.3, y: 0.5 },
  right: { x: 0.7, y: 0.5 },
  top: { x: 0.5, y: 0.5 },
};

// ---- Blank (default) constructor state -------------------------------------

/**
 * Fresh constructor-field defaults — the geometry/appearance baseline a preset
 * apply (and the "blank" preset) resets to. Mirrors the constructor half of the
 * wizard's `DEFAULTS`; contact / context fields are intentionally absent here
 * because they're preserved from the current form values, not reset.
 */
function blankConstructorFields(): Pick<
  PrintRequestInput,
  | "productType"
  | "widthMm"
  | "depthMm"
  | "heightMm"
  | "wallThicknessMm"
  | "shape"
  | "cornerRadiusMm"
  | "sectionsCount"
  | "hasHoles"
  | "holesDescription"
  | "hasFasteners"
  | "fastenersDescription"
  | "hasDecoration"
  | "decorationDescription"
  | "appearance"
  | "design"
  | "accessories"
  | "lid"
> {
  return {
    productType: "" as PrintRequestInput["productType"],
    widthMm: 180,
    depthMm: 120,
    heightMm: 60,
    wallThicknessMm: 2.0,
    shape: "rectangular",
    cornerRadiusMm: 0,
    sectionsCount: 0,
    hasHoles: false,
    holesDescription: "",
    hasFasteners: false,
    fastenersDescription: "",
    hasDecoration: false,
    decorationDescription: "",
    appearance: createDefaultAppearance(),
    design: { baseShape: { ...DEFAULT_DESIGN_BASE_SHAPE }, elements: [] },
    accessories: [],
    lid: createDefaultLid(),
  };
}

// ---- Catalogue -------------------------------------------------------------

export const CONSTRUCTOR_PRESETS: readonly ConstructorPreset[] = [
  {
    id: "boxWithLid",
    title: "Коробка с крышкой",
    description:
      "Прямоугольная коробка со скруглёнными углами, плоской накладной крышкой и ручкой спереди.",
    recommendedFor: "Хранение мелочей, подарочная упаковка",
    chips: ["крышка", "скругление", "ручка"],
    frontHandles: 1,
    values: {
      productType: "box",
      widthMm: 120,
      depthMm: 80,
      heightMm: 50,
      wallThicknessMm: 2.0,
      cornerRadiusMm: 10,
      design: {
        baseShape: { ...DEFAULT_DESIGN_BASE_SHAPE, kind: "roundedRectangle", cornerRadiusMm: 10 },
        elements: [],
      },
      lid: { ...createDefaultLid(), enabled: true, type: "flat", fit: "overlay" },
    },
  },
  {
    id: "sectionedOrganizer",
    title: "Органайзер с секциями",
    description:
      "Невысокий органайзер со скруглёнными углами и четырьмя секциями-перегородками.",
    recommendedFor: "Сортировка канцелярии, метизов, мелких деталей",
    chips: ["секции", "скругление"],
    values: {
      productType: "organizer",
      widthMm: 160,
      depthMm: 100,
      heightMm: 45,
      wallThicknessMm: 2.0,
      cornerRadiusMm: 6,
      sectionsCount: 4,
      design: {
        baseShape: { ...DEFAULT_DESIGN_BASE_SHAPE, kind: "roundedRectangle", cornerRadiusMm: 6 },
        elements: [],
      },
    },
  },
  {
    id: "panelWithHoles",
    title: "Панель с отверстиями",
    description:
      "Тонкая плоская панель с монтажным отверстием — основа для креплений и подвеса.",
    recommendedFor: "Монтажные пластины, кронштейны, держатели",
    chips: ["отверстия", "плоская"],
    values: {
      productType: "stand",
      widthMm: 120,
      depthMm: 80,
      heightMm: 8,
      wallThicknessMm: 2.0,
      cornerRadiusMm: 0,
      hasHoles: true,
      holesDescription:
        "Монтажное отверстие по центру верхней части. Уточните диаметр и расположение.",
      design: {
        baseShape: { ...DEFAULT_DESIGN_BASE_SHAPE, kind: "rectangle", cornerRadiusMm: 0 },
        elements: [],
      },
    },
  },
  {
    id: "textPlaque",
    title: "Табличка с текстом",
    description:
      "Плоская табличка в форме «капсулы» с надписью на верхней поверхности.",
    recommendedFor: "Таблички, бейджи, указатели, шильды",
    chips: ["текст", "плоская"],
    values: {
      productType: "other",
      widthMm: 140,
      depthMm: 60,
      heightMm: 6,
      wallThicknessMm: 2.0,
      cornerRadiusMm: 0,
      design: {
        baseShape: { ...DEFAULT_DESIGN_BASE_SHAPE, kind: "pill" },
        elements: [],
      },
      appearance: {
        ...createDefaultAppearance(),
        textDecoration: {
          ...createDefaultAppearance().textDecoration,
          enabled: true,
          text: "Ваш текст",
          placement: "top",
        },
      },
    },
  },
  {
    id: "blank",
    title: "Пустой шаблон",
    description:
      "Сбросить параметры изделия к значениям по умолчанию. Контакты и комментарий сохранятся.",
    recommendedFor: "Начать настройку с чистого листа",
    chips: ["сброс"],
    values: {},
  },
];

export function getConstructorPreset(
  id: ConstructorPresetId,
): ConstructorPreset | undefined {
  return CONSTRUCTOR_PRESETS.find((p) => p.id === id);
}

// ---- Confirmation gate -----------------------------------------------------

/**
 * True when the user has hand-made constructor work that a preset would
 * replace: any user-authored design element, or an image element carrying data.
 * System-managed elements (holes / fasteners / decor / textDecoration) don't
 * count — they're derived from toggles and re-created by presets anyway. Used by
 * the picker to decide whether to show a "this will replace your settings"
 * confirmation before applying.
 */
export function presetApplyNeedsConfirm(
  current: Pick<PrintRequestInput, "design">,
): boolean {
  const elements = current.design?.elements;
  if (!Array.isArray(elements)) return false;
  return elements.some((el) => {
    const source = el?.source ?? "user";
    if (source === "user") return true;
    // An image dropped in by the user carries data worth protecting.
    if (el?.type === "image" && typeof el.imageDataUrl === "string" && el.imageDataUrl.length > 0) {
      return true;
    }
    return false;
  });
}

// ---- Apply -----------------------------------------------------------------

/** Build the design.elements a preset implies, with freshly-generated ids. */
function buildPresetElements(
  values: ConstructorPresetValues,
): DesignElement[] {
  const elements: DesignElement[] = [];

  if (values.hasHoles) {
    elements.push(createHoleElement());
  }
  if (values.hasFasteners) {
    elements.push(...createFastenerElements());
  }
  if (values.hasDecoration) {
    // Mirror the Features-step behaviour: a decorative overlay element.
    elements.push(createDesignElement("decor", "overlay"));
  }

  const text = values.appearance?.textDecoration;
  if (text?.enabled && text.text) {
    const placement = (text.placement ?? "front") as TextPlacement;
    const center = TEXT_PLACEMENT_CENTER[placement];
    elements.push(
      createTextDecorationElement({
        text: text.text,
        fillColor: text.colorHex ?? createDefaultAppearance().textDecoration.colorHex,
        x: center.x,
        y: center.y,
      }),
    );
  }

  return elements;
}

/**
 * Produce a complete `PrintRequestInput` that applies `preset` on top of the
 * user's `current` form values:
 *   1. start from the blank constructor defaults (so switching presets never
 *      leaves stale geometry behind);
 *   2. preserve the user's contact / context / material fields from `current`;
 *   3. overlay the preset's declarative `values`;
 *   4. generate the implied design elements (holes / fasteners / decor / text)
 *      and front handles with fresh ids;
 *   5. mirror the chosen base shape onto the legacy `shape` field and sync the
 *      `design.baseShape` dimensions to the numeric width/depth so every preview
 *      and server validation reads a consistent geometry.
 *
 * The result is meant to be handed to `react-hook-form`'s `reset()`. No preset
 * id is included anywhere — presets never touch the payload.
 */
export function applyConstructorPresetValues(
  current: PrintRequestInput,
  preset: ConstructorPreset,
): PrintRequestInput {
  const blank = blankConstructorFields();
  const v = preset.values;

  // (1)+(2) baseline = blank constructor fields + preserved user context.
  const next: PrintRequestInput = { ...current, ...blank };
  for (const key of PRESERVED_FIELDS) {
    // Each preserved field keeps the user's current value (already present in
    // `current`, copied above) — listed explicitly for intent / auditing.
    (next as Record<string, unknown>)[key] = current[key];
  }

  // (3) overlay simple scalar / string / boolean preset fields.
  if (v.productType !== undefined) next.productType = v.productType;
  if (v.widthMm !== undefined) next.widthMm = v.widthMm;
  if (v.depthMm !== undefined) next.depthMm = v.depthMm;
  if (v.heightMm !== undefined) next.heightMm = v.heightMm;
  if (v.wallThicknessMm !== undefined) next.wallThicknessMm = v.wallThicknessMm;
  if (v.cornerRadiusMm !== undefined) next.cornerRadiusMm = v.cornerRadiusMm;
  if (v.sectionsCount !== undefined) next.sectionsCount = v.sectionsCount;
  if (v.hasHoles !== undefined) next.hasHoles = v.hasHoles;
  if (v.holesDescription !== undefined) next.holesDescription = v.holesDescription;
  if (v.hasFasteners !== undefined) next.hasFasteners = v.hasFasteners;
  if (v.fastenersDescription !== undefined)
    next.fastenersDescription = v.fastenersDescription;
  if (v.hasDecoration !== undefined) next.hasDecoration = v.hasDecoration;
  if (v.decorationDescription !== undefined)
    next.decorationDescription = v.decorationDescription;

  // Lid: blank disabled default unless the preset enables it.
  const lid: LidSettings = { ...createDefaultLid(), ...(v.lid ?? {}) } as LidSettings;
  next.lid = lid;

  // Appearance: keep the user's colour / finish / pattern, but reset the
  // text-decoration bridge (its design element is rebuilt below) and overlay any
  // preset appearance on top.
  const currentAppearance = (current.appearance ?? createDefaultAppearance()) as Appearance;
  const mergedAppearance: Appearance = {
    ...createDefaultAppearance(),
    ...currentAppearance,
    pattern: { ...createDefaultAppearance().pattern, ...currentAppearance.pattern },
    // Default = disabled; a preset (e.g. the plaque) re-enables it just below.
    textDecoration: { ...createDefaultAppearance().textDecoration },
  };
  if (v.appearance) {
    Object.assign(mergedAppearance, {
      ...v.appearance,
      pattern: { ...mergedAppearance.pattern, ...v.appearance.pattern },
      textDecoration: {
        ...mergedAppearance.textDecoration,
        ...v.appearance.textDecoration,
      },
    });
  }
  next.appearance = mergedAppearance;

  // (5) base shape + legacy mirroring.
  const presetBaseShape = v.design?.baseShape;
  const kind: BaseShapeKind =
    (presetBaseShape?.kind as BaseShapeKind | undefined) ?? "rectangle";
  const cornerRadiusMm = next.cornerRadiusMm ?? 0;
  next.shape = baseKindToLegacyShape(kind);

  const design: DesignSettings = {
    baseShape: {
      ...DEFAULT_DESIGN_BASE_SHAPE,
      ...(presetBaseShape ?? {}),
      kind,
      widthMm: next.widthMm,
      heightMm: next.depthMm,
      cornerRadiusMm,
    },
    // (4) elements derived from the preset intent, with fresh ids.
    elements: buildPresetElements({ ...v, appearance: mergedAppearance }),
  };
  next.design = design;

  // (4) front-mounted handles, fresh ids.
  next.accessories = Array.from({ length: preset.frontHandles ?? 0 }, () =>
    createHandleAccessory({ side: "front" }),
  ) as PrintRequestInput["accessories"];

  return next;
}
